### ISSUE TITLE
Company List

### ISSUE THREAD

**Issue by Wmaxlees** [amc-ucdenver/website#7]
As a web developer, I need to know where the list of company supporters comes from and the form of that content

**Comment by Wmaxlees** [comment]
I'm thinking xml list. Thoughts?

**Comment by robfitzgerald** [comment]
Ah this is good.  a list of companies that have supported us in the past.
this may just live with the events collection.  an event may benefit from having a "company" field that stores this data.  getting the complete list of companies would be done by a query to that collection returning all unique entries in the company field.  again, json not xml, if we are using mongo/angular, as those technologies communicate to each other using json.

**Comment by robfitzgerald** [comment]
this would limit us, however, to listing company supporters that have valid event entries.  so, like, if we can't find data on an event involving a company, but we know we did something with them, we wouldn't be able to add them because the list would be based on stored events.

also!  if we do still choose the events: [ { company: "" } ] approach, we need to allow company to be an array, so that multiple companies can be listed with an event.

**Comment by Wmaxlees** [comment]
Hmm. I like that it queries the event database. That could save us some trouble. But there are companies that just straight up donate money, right?

I think our server should have a db of contributors. It will automatically add any unique companies to this list when we add events with contributors. But we can still add new companies if they are not attached to any events.

**Comment by robfitzgerald** [comment]
Oh ya that's a better idea!

**Comment by Wmaxlees** [comment]
So as far as the actual company object, maybe something like this:

    {
        name: "company name,
        website: "company website"
    }

We could add logos as an enhancement if we want.
