### ISSUE TITLE
Officer Information

### ISSUE THREAD

**Issue by Wmaxlees** [amc-ucdenver/website#8]
As a web developer, I need to know where the officer contact information is coming from and the form the data will take

**Comment by Wmaxlees** [comment]
I'm thinking xml for this as well

**Comment by robfitzgerald** [comment]
i'm assuming we will write an admin page which allows CRUD access to an officers collection.
(in mongodb, a table is called a collection; a row is called a document).  officer data will be added/removed from the officers collection.  pages displaying officers will load that content from the collection via a query.

if the database is mongodb and the page angular, we will want to use json instead of xml as our data format.  mongo/ng are built to communicate via json.

**Comment by Wmaxlees** [comment]
{
        name: "officer name",
        position: "position in ACM",
        email: "email address",
        photo: "photo url"
    }

That's probably all we need right?

**Comment by robfitzgerald** [comment]
Unless we want a class (fresh/soph/etc), and maybe a bio/personal blurb?

**Comment by Wmaxlees** [comment]
I'd be fine with that. We should have the system only require name, position, email and then have the other 2 + the class and bio as optional

**Comment by Wmaxlees** [comment]
Maybe website url too. We could put github repository or whatever in there

**Comment by robfitzgerald** [comment]
Oh totally

**Comment by Wmaxlees** [comment]
Okay, so:

    {
        name: "officer name",
        position: "position in ACM",
        email: "email address",
        photo: "photo url",
        year: "year of school",
        bio: "short biography"
    }

with only name, position, and email required.

**Comment by robfitzgerald** [comment]
sounds good.
i think the best practice is to place "required" and "optional" handling
entirely in the web form, validated by html or angular.

**Comment by Wmaxlees** [comment]
[Officer Information](https://github.com/amc-ucdenver/website/wiki/3.1-Officer-Information)
